### ISSUE TITLE
Set up CIT

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#15]
We would like to make the notebooks useable outside the jupyterlab instance, for longevity and general usefulness. This ties in well with our CIT (continuuous integration and testing) aspirations, so here's an epic to get this going:

* [x] Figure out how to unit/continuously test notebooks, preferably with Travis CI - this needs setting up sooner rather than later, so we can use it to check our tutorials as we go. #17 Deploy the notebook outputs in html format to a web gallery, so they can be printed out etc
* [x] Make a first tutorial notebook to exercise DM Stack (and hence check that people are set up correctly). This could be “Hello Sky” (#13 ) or something else. This will be useful for:
* [x] Extend CIT to include use of docker to recreate Stack v15 environment

**Comment by drphilmarshall** [comment]
This should have been closed by the messages in #62...
