### ISSUE TITLE
Starting up our Phase 1 Projects

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#50]
Hi @LSSTScienceCollaborations/dm-stack-club , 

Let's get our phase 1 projects started! These are the tutorial notebooks that we will show at the August PCW, and use as starting points for phase 2 this fall. We've been noting down our interests in the [topic list in the seedling notebooks doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#heading=h.txq6h6bpxzkd), and now it's time to issue ourselves and get to work! Here's what we each need to do:

1. **Write an issue,** [like #48](https://github.com/LSSTScienceCollaborations/DMStackClub/issues/48), that describes what your phase 1 project is going to be. We'll label these threads as "project" and leave them open so that we can use them for targeted discussion. 

2. **Make a branch to work in**, called something like [`project/DIA/drphilmarshall`](https://github.com/LSSTScienceCollaborations/DMStackClub/tree/project/DIA/drphilmarshall), and get started on your first notebook. You should also edit the various README files as needed, to keep track of your tutorials. 

3. **Push your branch and open a pull request,** [like #49 ], as soon as you have made your first commit, so that it's easy for the rest of us to see your work in progress and help you out. 

4. At the next Stack Club session, be prepared to say, in 30 secs or so, what you aim to achieve during that session (eg the progress you want to make on one of your notebooks, the help you are hoping to get from the rest of the club, the finding of someone else to work on one of your notebooks, etc). 

Below is a checklist of rough project ideas and their possible executors that have come up in Stack Club sessions so far, which I will use to ping people. Questions and comments most welcome, either in this thread or on Slack. Let's go! :-)

### Tentatively Proposed Projects
From the [topic list doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#heading=h.txq6h6bpxzkd):
* [x] @Madejski : Getting to know the Butler #59 
* [ ] Open: Guided tour of an afwtable Object #51 
* [x] @stargaser: Guided tour of a calexp Object #52
* [x] @andrewkbradshaw: Reduction and analysis of Beam Simulator images #58
* [x] @kadrlica : Low Surface Brightness galaxy detection #54
* [x] @drphilmarshall : DIA walkthrough #48
* [ ] @johannct : Exercising the validation packages 
* [x] @heather999 : using Docker #16

**Comment by drphilmarshall** [comment]
The Phase 1 projects are well underway; the guidelines for starting projects need capturing in our docs (#8) but we can close this.
