### ISSUE TITLE
Start experimental module library

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/StackClub#79]
... to enable useful functions etc to be kept in small module files and imported as needed. `whereis` (issue #76) is a good first example of this; @jtmyles and I also want to be able to import modules after downloading them from the web. It would be nice to be able to [import notebooks](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Importing%20Notebooks.html) as well (h/t to @jonathansick for that pointer).

Update: This issue turned out to be an epic, with a bunch of issues being addressed by the same PR, #80 
* [ ] #20 Include modules, packaged up (also this issue)
* [ ] #76 Module to help find the source code from inside a notebook
* [ ] #81 API docs for the stackclub library
